db.peliculas.insertOne( {'pelicula':'Titanic', 'estreno': 1998 } )
db.peliculas.insertOne( {'pelicula':'Avatar', 'estreno': 2009 } )
db.peliculas.insertOne( {'pelicula':'Los Vengadores', 'estreno': 2012 } )
db.peliculas.insertOne( {'pelicula':'La vida es bella', 'estreno': 1997 } )
db.peliculas.insertOne( {'pelicula':'Pearl Harbor', 'estreno': 2001 } )
db.peliculas.insertOne( {'pelicula':'Dirty Dancing', 'estreno': 1987 } )
db.peliculas.insertOne( {'pelicula':'Forrest Gum', 'estreno': 1994 } )
db.peliculas.insertOne( {'pelicula':'Gladiator', 'estreno': 2000 } )
db.peliculas.insertOne( {'pelicula':'Salvar al soldado Ryan', 'estreno': 1998 } )
db.peliculas.insertOne( {'pelicula':'Rocky', 'estreno': 1976 } )